volumes:
    duodev_dev_data:
    backend_node_modules:
    backend_app_node_modules:
    admin_back_node_modules:
    admin_back_app_node_modules:
    frontend_node_modules:
    frontend_app_node_modules:
    admin_front_node_modules:
    admin_front_app_node_modules:

services:
    backend:
        build:
            target: dev
        command: npm run start:dev
        volumes:
            - ./apps/backend:/app/apps/backend:z
            - ./packages:/app/packages:z
            - backend_node_modules:/app/node_modules
            - backend_app_node_modules:/app/apps/backend/node_modules

    admin-back:
        build:
            target: dev
        command: npm run start:dev
        volumes:
            - ./apps/admin/admin-back:/app/apps/admin/admin-back:z
            - ./packages:/app/packages:z
            - admin_back_node_modules:/app/node_modules
            - admin_back_app_node_modules:/app/apps/admin/admin-back/node_modules

    frontend:
        build:
            target: dev
        command: npm run dev -- --host
        stdin_open: true
        tty: true
        volumes:
            - ./apps/frontend:/app/apps/frontend:z
            - ./packages:/app/packages:z
            - frontend_node_modules:/app/node_modules
            - frontend_app_node_modules:/app/apps/frontend/node_modules

    admin-front:
        build:
            target: dev
        command: npm run dev -- --host
        stdin_open: true
        tty: true
        volumes:
            - ./apps/admin/admin-front:/app/apps/admin/admin-front:z
            - ./packages:/app/packages:z
            - admin_front_node_modules:/app/node_modules
            - admin_front_app_node_modules:/app/apps/admin/admin-front/node_modules

    postgres:
        ports:
            - 8030:5432
        volumes:
            - duodev_dev_data:/var/lib/postgresql/
