/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as modulesCategoriasRouteImport } from './routes/(modules)/Categorias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const modulesCategoriasRoute = modulesCategoriasRouteImport.update({
  id: '/(modules)/Categorias',
  path: '/Categorias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Categorias': typeof modulesCategoriasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Categorias': typeof modulesCategoriasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(modules)/Categorias': typeof modulesCategoriasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Categorias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Categorias'
  id: '__root__' | '/' | '/(modules)/Categorias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  modulesCategoriasRoute: typeof modulesCategoriasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(modules)/Categorias': {
      id: '/(modules)/Categorias'
      path: '/Categorias'
      fullPath: '/Categorias'
      preLoaderRoute: typeof modulesCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  modulesCategoriasRoute: modulesCategoriasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
