/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as modulesConteudoIndexRouteImport } from './routes/(modules)/conteudo/index'
import { Route as modulesConteudoCategoriaIdRouteImport } from './routes/(modules)/conteudo/$categoriaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const modulesConteudoIndexRoute = modulesConteudoIndexRouteImport.update({
  id: '/(modules)/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const modulesConteudoCategoriaIdRoute =
  modulesConteudoCategoriaIdRouteImport.update({
    id: '/(modules)/conteudo/$categoriaId',
    path: '/conteudo/$categoriaId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conteudo/$categoriaId': typeof modulesConteudoCategoriaIdRoute
  '/conteudo/': typeof modulesConteudoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conteudo/$categoriaId': typeof modulesConteudoCategoriaIdRoute
  '/conteudo': typeof modulesConteudoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(modules)/conteudo/$categoriaId': typeof modulesConteudoCategoriaIdRoute
  '/(modules)/conteudo/': typeof modulesConteudoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conteudo/$categoriaId' | '/conteudo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conteudo/$categoriaId' | '/conteudo'
  id:
    | '__root__'
    | '/'
    | '/(modules)/conteudo/$categoriaId'
    | '/(modules)/conteudo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  modulesConteudoCategoriaIdRoute: typeof modulesConteudoCategoriaIdRoute
  modulesConteudoIndexRoute: typeof modulesConteudoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(modules)/conteudo/': {
      id: '/(modules)/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof modulesConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(modules)/conteudo/$categoriaId': {
      id: '/(modules)/conteudo/$categoriaId'
      path: '/conteudo/$categoriaId'
      fullPath: '/conteudo/$categoriaId'
      preLoaderRoute: typeof modulesConteudoCategoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  modulesConteudoCategoriaIdRoute: modulesConteudoCategoriaIdRoute,
  modulesConteudoIndexRoute: modulesConteudoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
